------------------------------------------------------------------------------------------------------------------------
--  Copyright (c) 2015, Luke A. Guest et al
--  All rights reserved.
--
--  Redistribution and use in source and binary forms, with or without
--  modification, are permitted provided that the following conditions are met:
--      * Redistributions of source code must retain the above copyright
--        notice, this list of conditions and the following disclaimer.
--      * Redistributions in binary form must reproduce the above copyright
--        notice, this list of conditions and the following disclaimer in the
--        documentation and/or other materials provided with the distribution.
--      * Neither the name of Luke A. Guest nor the
--        names of its contributors may be used to endorse or promote products
--        derived from this software without specific prior written permission.
--
--  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
--  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
--  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
--  DISCLAIMED. IN NO EVENT SHALL Luke A. Guest BE LIABLE FOR ANY
--  DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
--  (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
--  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
--  ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
--  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
--  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
------------------------------------------------------------------------------------------------------------------------
with Interfaces.C; use Interfaces.C;

package SPIRV is

   --  unsupported macro: _VERSION 10000
   --  unsupported macro: _REVISION 2
   subtype Id is unsigned;  -- spirv.h:51

   Magic_Number     : unsigned := 16#0723_0203#;
   Version          : unsigned := 16#0001_0000#;
   Revision         : unsigned := 2;
   Op_Code_Mask     : unsigned := 16#0000_ffff#;
   Word_Count_Shift : unsigned := 16;

   type Source_Language is
     (Unknown,
      ESSL,
      GLSL,
      OpenCL_C,
      OpenCL_CPP) with
     Convention => C;

   type Execution_Model is
     (Vertex,
      Tessellation_Control,
      Tessellation_Evaluation,
      Geometry,
      Fragment,
      GLCompute,
      Kernel) with
     Convention => C;

   type Addressing_Model is
     (Logical,
      Physical_32,
      Physical_64) with
     Convention => C;

   type Memory_Model is
     (Simple,
      GLSL_450,
      OpenCL) with
     Convention => C;

   type Execution_Mode is
     (Invocations,
      Spacing_Equal,
      Spacing_Fractional_Even,
      Spacing_Fractional_Odd,
      Vertex_Order_CW,
      Vertex_Order_CCW,
      Pixel_Center_Integer,
      Origin_Upper_Left,
      Origin_Lower_Left,
      Early_Fragment_Tests,
      Point_Mode,
      XFB,
      Depth_Replacing,
      Depth_Greater,
      Depth_Less,
      Depth_Unchanged,
      Local_Size,
      Local_Size_Hint,
      Input_Points,
      Input_Lines,
      Input_Lines_Adjacency,
      Triangles,
      Input_Triangles_Adjacency,
      Quads,
      Isolines,
      Output_Vertices,
      Output_Points,
      Output_Line_Strip,
      Output_Triangle_Strip,
      Vec_Type_Hint,
      Contraction_Off) with
     Convention => C;

   for Execution_Mode use
     (Invocations               => 0,
      Spacing_Equal             => 1,
      Spacing_Fractional_Even   => 2,
      Spacing_Fractional_Odd    => 3,
      Vertex_Order_CW           => 4,
      Vertex_Order_CCW          => 5,
      Pixel_Center_Integer      => 6,
      Origin_Upper_Left         => 7,
      Origin_Lower_Left         => 8,
      Early_Fragment_Tests      => 9,
      Point_Mode                => 10,
      XFB                       => 11,
      Depth_Replacing           => 12,
      Depth_Greater             => 14,
      Depth_Less                => 15,
      Depth_Unchanged           => 16,
      Local_Size                => 17,
      Local_Size_Hint           => 18,
      Input_Points              => 19,
      Input_Lines               => 20,
      Input_Lines_Adjacency     => 21,
      Triangles                 => 22,
      Input_Triangles_Adjacency => 23,
      Quads                     => 24,
      Isolines                  => 25,
      Output_Vertices           => 26,
      Output_Points             => 27,
      Output_Line_Strip         => 28,
      Output_Triangle_Strip     => 29,
      Vec_Type_Hint             => 30,
      Contraction_Off           => 31);

   type Storage_Class is
     (Class_Uniform_Constant,
      Class_Input,
      Class_Uniform,
      Class_Output,
      Class_Workgroup,
      Class_Cross_Workgroup,
      Class_Private,
      Class_Function,
      Class_Generic,
      Class_Push_Constant,
      Class_Atomic_Counter,
      Class_Image) with
     Convention => C;

   type Dimension is
     (One_D,
      Two_D,
      Three_D,
      Cube,
      Rectangle,
      Buffer,
      Subpass_Data) with
     Convention => C;

   type Sampler_Addressing_Mode is
     (None,
      Clamp_To_Edge,
      Clamp,
      Repeat,
      Repeat_Mirrored) with
     Convention => C;

   type Sampler_Filter_Mode is
     (Nearest,
      Linear) with
     Convention => C;

   type Image_Format is
     (Unknown,
      Rgba32f,
      Rgba16f,
      R32f,
      Rgba8,
      Rgba8Snorm,
      Rg32f,
      Rg16f,
      R11fG11fB10f,
      R16f,
      Rgba16,
      Rgb10A2,
      Rg16,
      Rg8,
      R16,
      R8,
      Rgba16Snorm,
      Rg16Snorm,
      Rg8Snorm,
      R16Snorm,
      R8Snorm,
      Rgba32i,
      Rgba16i,
      Rgba8i,
      R32i,
      Rg32i,
      Rg16i,
      Rg8i,
      R16i,
      R8i,
      Rgba32ui,
      Rgba16ui,
      Rgba8ui,
      R32ui,
      Rgb10a2ui,
      Rg32ui,
      Rg16ui,
      Rg8ui,
      R16ui,
      R8ui) with
     Convention => C;

   type Image_Channel_Order is
     (R,
      A,
      RG,
      RA,
      RGB,
      RGBA,
      BGRA,
      ARGB,
      Intensity,
      Luminance,
      Rx,
      RGx,
      RGBx,
      Depth,
      DepthStencil,
      sRGB,
      sRGBx,
      sRGBA,
      sBGRA) with
     Convention => C;

   type Image_Channel_Data_Type is
     (SnormInt8,
      SnormInt16,
      UnormInt8,
      UnormInt16,
      UnormShort565,
      UnormShort555,
      UnormInt101010,
      SignedInt8,
      SignedInt16,
      SignedInt32,
      UnsignedInt8,
      UnsignedInt16,
      UnsignedInt32,
      HalfFloat,
      Float,
      UnormInt24,
      UnormInt101010_2) with
     Convention => C;

   type Image_Operands_Shift is
     (BiasShift,
      LodShift,
      GradShift,
      ConstOffsetShift,
      OffsetShift,
      ConstOffsetsShift,
      SampleShift,
      MinLodShift) with
     Convention => C;

   subtype Image_Operands_Mask is unsigned;

   Image_Operands_Mask_None          : constant Image_Operands_Mask := 0;
   Image_Operands_Bias_Mask          : constant Image_Operands_Mask := 1;
   Image_Operands_LOD_Mask           : constant Image_Operands_Mask := 2;
   Image_Operands_Grad_Mask          : constant Image_Operands_Mask := 4;
   Image_Operands_Const_Offset_Mask  : constant Image_Operands_Mask := 8;
   Image_Operands_Offset_Mask        : constant Image_Operands_Mask := 16;
   Image_Operands_Const_Offsets_Mask : constant Image_Operands_Mask := 32;
   Image_Operands_Sample_Mask        : constant Image_Operands_Mask := 64;
   Image_Operands_Min_LOD_Mask       : constant Image_Operands_Mask := 128;

   type FP_Fast_Math_Mode_Shift is
     (Not_NaN_Shift,
      Not_Inf_Shift,
      NSZ_Shift,
      Allow_Recip_Shift,
      Fast_Shift) with
     Convention => C;

   subtype FP_Fast_Math_Mode_Mask is unsigned;

   FP_Fast_Math_Mode_Mask_None        : constant FP_Fast_Math_Mode_Mask := 0;
   FP_Fast_Math_Mode_Not_NaN_Mask     : constant FP_Fast_Math_Mode_Mask := 1;
   FP_Fast_Math_Mode_Not_Inf_Mask     : constant FP_Fast_Math_Mode_Mask := 2;
   FP_Fast_Math_Mode_NSZ_Mask         : constant FP_Fast_Math_Mode_Mask := 4;
   FP_Fast_Math_Mode_Allow_Recip_Mask : constant FP_Fast_Math_Mode_Mask := 8;
   FP_Fast_Math_Mode_Fast_Mask        : constant FP_Fast_Math_Mode_Mask := 16;

   type FP_Rounding_Mode is
     (RTE,
      RTZ,
      RTP,
      RTN) with
     Convention => C;

   type Linkage_Type is
     (Export,
      Import) with
     Convention => C;

   type Access_Qualifier is
     (Read_Only,
      Write_Only,
      Read_Write) with
     Convention => C;

   type Function_Parameter_Attribute is
     (Zero_Extended,    --  Zext
      Sign_Extended,    --  Sext
      By_Val,
      Structure_Return, --  Sret
      No_Alias,
      No_Capture,
      No_Write,
      No_Read_Write) with
     Convention => C;

   type Decoration is
     (Decoration_Relaxed_Precision,
      Decoration_Spec_Id,
      Decoration_Block,
      Decoration_Buffer_Block,
      Decoration_Row_Major,
      Decoration_Col_Major,
      Decoration_Array_Stride,
      Decoration_Matrix_Stride,
      Decoration_GLSL_Shared,
      Decoration_GLSL_Packed,
      Decoration_C_Packed,
      Decoration_Built_In,
      Decoration_No_Perspective,
      Decoration_Flat,
      Decoration_Patch,
      Decoration_Centroid,
      Decoration_Sample,
      Decoration_Invariant,
      Decoration_Restrict,
      Decoration_Aliased,
      Decoration_Volatile,
      Decoration_Constant,
      Decoration_Coherent,
      Decoration_Non_Writable,
      Decoration_Non_Readable,
      Decoration_Uniform,
      Decoration_Saturated_Conversion,
      Decoration_Stream,
      Decoration_Location,
      Decoration_Component,
      Decoration_Index,
      Decoration_Binding,
      Decoration_Descriptor_Set,
      Decoration_Offset,
      Decoration_XFB_Buffer,
      Decoration_XFB_Stride,
      Decoration_Func_Param_Attr,
      Decoration_FP_Rounding_Mode,
      Decoration_FP_Fast_Math_Mode,
      Decoration_Linkage_Attributes,
      Decoration_No_Contraction,
      Decoration_Input_Attachment_Index,
      Decoration_Alignment) with
     Convention => C;

   for Decoration use
     (Decoration_Relaxed_Precision      => 0,
      Decoration_Spec_Id                => 1,
      Decoration_Block                  => 2,
      Decoration_Buffer_Block           => 3,
      Decoration_Row_Major              => 4,
      Decoration_Col_Major              => 5,
      Decoration_Array_Stride           => 6,
      Decoration_Matrix_Stride          => 7,
      Decoration_GLSL_Shared            => 8,
      Decoration_GLSL_Packed            => 9,
      Decoration_C_Packed               => 10,
      Decoration_Built_In               => 11,
      Decoration_No_Perspective         => 13,
      Decoration_Flat                   => 14,
      Decoration_Patch                  => 15,
      Decoration_Centroid               => 16,
      Decoration_Sample                 => 17,
      Decoration_Invariant              => 18,
      Decoration_Restrict               => 19,
      Decoration_Aliased                => 20,
      Decoration_Volatile               => 21,
      Decoration_Constant               => 22,
      Decoration_Coherent               => 23,
      Decoration_Non_Writable           => 24,
      Decoration_Non_Readable           => 25,
      Decoration_Uniform                => 26,
      Decoration_Saturated_Conversion   => 28,
      Decoration_Stream                 => 29,
      Decoration_Location               => 30,
      Decoration_Component              => 31,
      Decoration_Index                  => 32,
      Decoration_Binding                => 33,
      Decoration_Descriptor_Set         => 34,
      Decoration_Offset                 => 35,
      Decoration_XFB_Buffer             => 36,
      Decoration_XFB_Stride             => 37,
      Decoration_Func_Param_Attr        => 38,
      Decoration_FP_Rounding_Mode       => 39,
      Decoration_FP_Fast_Math_Mode      => 40,
      Decoration_Linkage_Attributes     => 41,
      Decoration_No_Contraction         => 42,
      Decoration_Input_Attachment_Index => 43,
      Decoration_Alignment              => 44);

   type Built_In is
     (Position,
      Point_Size,
      Clip_Distance,
      Cull_Distance,
      Vertex_Id,
      Instance_Id,
      Primitive_Id,
      Invocation_Id,
      Layer,
      Viewport_Index,
      Tess_Level_Outer,
      Tess_Level_Inner,
      Tess_Coord,
      Patch_Vertices,
      Frag_Coord,
      Point_Coord,
      Front_Facing,
      Sample_Id,
      Sample_Position,
      Sample_Mask,
      Frag_Depth,
      Helper_Invocation,
      Num_Workgroups,
      Workgroup_Size,
      Workgroup_Id,
      Local_Invocation_Id,
      Global_Invocation_Id,
      Local_Invocation_Index,
      Work_Dim,
      Global_Size,
      Enqueued_Workgroup_Size,
      Global_Offset,
      Global_Linear_Id,
      Subgroup_Size,
      Subgroup_Max_Size,
      Num_Subgroups,
      Num_Enqueued_Subgroups,
      Subgroup_Id,
      Subgroup_Local_Invocation_Id,
      Vertex_Index,
      Instance_Index) with
     Convention => C;

   for Built_In use
     (Position                     => 0,
      Point_Size                   => 1,
      Clip_Distance                => 3,
      Cull_Distance                => 4,
      Vertex_Id                    => 5,
      Instance_Id                  => 6,
      Primitive_Id                 => 7,
      Invocation_Id                => 8,
      Layer                        => 9,
      Viewport_Index               => 10,
      Tess_Level_Outer             => 11,
      Tess_Level_Inner             => 12,
      Tess_Coord                   => 13,
      Patch_Vertices               => 14,
      Frag_Coord                   => 15,
      Point_Coord                  => 16,
      Front_Facing                 => 17,
      Sample_Id                    => 18,
      Sample_Position              => 19,
      Sample_Mask                  => 20,
      Frag_Depth                   => 22,
      Helper_Invocation            => 23,
      Num_Workgroups               => 24,
      Workgroup_Size               => 25,
      Workgroup_Id                 => 26,
      Local_Invocation_Id          => 27,
      Global_Invocation_Id         => 28,
      Local_Invocation_Index       => 29,
      Work_Dim                     => 30,
      Global_Size                  => 31,
      Enqueued_Workgroup_Size      => 32,
      Global_Offset                => 33,
      Global_Linear_Id             => 34,
      Subgroup_Size                => 36,
      Subgroup_Max_Size            => 37,
      Num_Subgroups                => 38,
      Num_Enqueued_Subgroups       => 39,
      Subgroup_Id                  => 40,
      Subgroup_Local_Invocation_Id => 41,
      Vertex_Index                 => 42,
      Instance_Index               => 43);

   type Selection_Control_Shift is
     (Flatten_Shift,
      Dont_Flatten_Shift) with
     Convention => C;

   type Selection_Control_Mask is
     (Mask_None,
      Flatten_Mask,
      Dont_Flatten_Mask) with
     Convention => C;

   type Loop_Control_Shift is
     (Unroll_Shift,
      Dont_Unroll_Shift) with
     Convention => C;

   type Loop_Control_Mask is
     (Mask_None,
      Unroll_Mask,
      Dont_Unroll_Mask) with
     Convention => C;

   type Function_Control_Shift is
     (Inline_Shift,
      Dont_Inline_Shift,
      Pure_Shift,
      Constant_Shift) with
     Convention => C;

   subtype Function_Control_Mask is unsigned;

   Function_Control_Mask_None        : constant Function_Control_Mask := 0;
   Function_Control_Inline_Mask      : constant Function_Control_Mask := 1;
   Function_Control_Dont_Inline_Mask : constant Function_Control_Mask := 2;
   Function_Control_Pure_Mask        : constant Function_Control_Mask := 4;
   Function_Control_Constant_Mask    : constant Function_Control_Mask := 8;

   type Memory_Semantics_Shift is
     (Memory_Semantics_Acquire_Shift,
      Memory_Semantics_Release_Shift,
      Memory_Semantics_Acquire_Release_Shift,
      Memory_Semantics_Sequentially_Consistent_Shift,
      Memory_Semantics_Uniform_Memory_Shift,
      Memory_Semantics_Subgroup_Memory_Shift,
      Memory_Semantics_Workgroup_Memory_Shift,
      Memory_Semantics_Cross_Workgroup_Memory_Shift,
      Memory_Semantics_Atomic_Counter_Memory_Shift,
      Memory_Semantics_Image_Memory_Shift) with
     Convention => C;

   for Memory_Semantics_Shift use
     (Memory_Semantics_Acquire_Shift                 => 1,
      Memory_Semantics_Release_Shift                 => 2,
      Memory_Semantics_Acquire_Release_Shift         => 3,
      Memory_Semantics_Sequentially_Consistent_Shift => 4,
      Memory_Semantics_Uniform_Memory_Shift          => 6,
      Memory_Semantics_Subgroup_Memory_Shift         => 7,
      Memory_Semantics_Workgroup_Memory_Shift        => 8,
      Memory_Semantics_Cross_Workgroup_Memory_Shift  => 9,
      Memory_Semantics_Atomic_Counter_Memory_Shift   => 10,
      Memory_Semantics_Image_Memory_Shift            => 11);

   subtype Memory_Semantics_Mask is unsigned;

   Memory_Semantics_Mask_None                    : constant Memory_Semantics_Mask := 0;
   Memory_Semantics_Acquire_Mask                 : constant Memory_Semantics_Mask := 2;
   Memory_Semantics_Release_Mask                 : constant Memory_Semantics_Mask := 4;
   Memory_Semantics_Acquire_Release_Mask         : constant Memory_Semantics_Mask := 8;
   Memory_Semantics_Sequentially_Consistent_Mask : constant Memory_Semantics_Mask := 16;
   Memory_Semantics_Uniform_Memory_Mask          : constant Memory_Semantics_Mask := 64;
   Memory_Semantics_Subgroup_Memory_Mask         : constant Memory_Semantics_Mask := 128;
   Memory_Semantics_Workgroup_Memory_Mask        : constant Memory_Semantics_Mask := 256;
   Memory_Semantics_Cross_Workgroup_Memory_Mask  : constant Memory_Semantics_Mask := 512;
   Memory_Semantics_Atomic_Counter_Memory_Mask   : constant Memory_Semantics_Mask := 1024;
   Memory_Semantics_Image_Memory_Mask            : constant Memory_Semantics_Mask := 2048;

   type Memory_Access_Shift is
     (Volatile_Shift,
      Aligned_Shift,
      Nontemporal_Shift) with
     Convention => C;

   subtype Memory_Access_Mask is unsigned;

   Memory_Access_Mask_None        : constant Memory_Access_Mask := 0;
   Memory_Access_Volatile_Mask    : constant Memory_Access_Mask := 1;
   Memory_Access_Aligned_Mask     : constant Memory_Access_Mask := 2;
   Memory_Access_Nontemporal_Mask : constant Memory_Access_Mask := 4;

   type Scope is
     (Cross_Device,
      Device,
      Workgroup,
      Subgroup,
      Invocation) with
     Convention => C;

   type Group_Operation is
     (Reduce,
      Inclusive_Scan,
      Exclusive_Scan) with
     Convention => C;

   type Kernel_Enqueue_Flags is
     (No_Wait,
      Wait_Kernel,
      Wait_WorkGroup) with
     Convention => C;

   type Kernel_Profiling_Info_Shift is
     (Info_Cmd_Exec_Time_Shift) with
   Convention => C;

   type Kernel_Profiling_Info_Mask is
     (Mask_None,
      Cmd_Exec_Time_Mask) with
     Convention => C;

   type Capability is
     (Matrix,
      Shader,
      Geometry,
      Tessellation,
      Addresses,
      Linkage,
      Kernel,
      Vector16,
      Float16_Buffer,
      Float16,
      Float64,
      Int64,
      Int64_Atomics,
      Image_Basic,
      Image_Read_Write,
      Image_Mipmap,
      Pipes,
      Groups,
      Device_Enqueue,
      Literal_Sampler,
      Atomic_Storage,
      Int16,
      Tessellation_Point_Size,
      Geometry_Point_Size,
      Image_Gather_Extended,
      Storage_Image_Multisample,
      Uniform_Buffer_Array_Dynamic_Indexing,
      Sampled_Image_Array_Dynamic_Indexing,
      Storage_Buffer_Array_Dynamic_Indexing,
      Storage_Image_Array_Dynamic_Indexing,
      Clip_Distance,
      Cull_Distance,
      Image_Cube_Array,
      Sample_Rate_Shading,
      Image_Rect,
      Sampled_Rect,
      Generic_Pointer,
      Int8,
      Input_Attachment,
      Sparse_Residency,
      Min_LOD,
      Sampled_1D,
      Image_1D,
      Sampled_Cube_Array,
      Sampled_Buffer,
      Image_Buffer,
      Image_MS_Array,
      Storage_Image_Extended_Formats,
      Image_Query,
      Derivative_Control,
      Interpolation_Function,
      Transform_Feedback,
      Geometry_Streams,
      Storage_Image_Read_Without_Format,
      Storage_Image_Write_Without_Format) with
     Convention => C;

   for Capability use
     (Matrix                                => 0,
      Shader                                => 1,
      Geometry                              => 2,
      Tessellation                          => 3,
      Addresses                             => 4,
      Linkage                               => 5,
      Kernel                                => 6,
      Vector16                              => 7,
      Float16_Buffer                        => 8,
      Float16                               => 9,
      Float64                               => 10,
      Int64                                 => 11,
      Int64_Atomics                         => 12,
      Image_Basic                           => 13,
      Image_Read_Write                      => 14,
      Image_Mipmap                          => 15,
      Pipes                                 => 17,
      Groups                                => 18,
      Device_Enqueue                        => 19,
      Literal_Sampler                       => 20,
      Atomic_Storage                        => 21,
      Int16                                 => 22,
      Tessellation_Point_Size               => 23,
      Geometry_Point_Size                   => 24,
      Image_Gather_Extended                 => 25,
      Storage_Image_Multisample             => 27,
      Uniform_Buffer_Array_Dynamic_Indexing => 28,
      Sampled_Image_Array_Dynamic_Indexing  => 29,
      Storage_Buffer_Array_Dynamic_Indexing => 30,
      Storage_Image_Array_Dynamic_Indexing  => 31,
      Clip_Distance                         => 32,
      Cull_Distance                         => 33,
      Image_Cube_Array                      => 34,
      Sample_Rate_Shading                   => 35,
      Image_Rect                            => 36,
      Sampled_Rect                          => 37,
      Generic_Pointer                       => 38,
      Int8                                  => 39,
      Input_Attachment                      => 40,
      Sparse_Residency                      => 41,
      Min_LOD                               => 42,
      Sampled_1D                            => 43,
      Image_1D                              => 44,
      Sampled_Cube_Array                    => 45,
      Sampled_Buffer                        => 46,
      Image_Buffer                          => 47,
      Image_MS_Array                        => 48,
      Storage_Image_Extended_Formats        => 49,
      Image_Query                           => 50,
      Derivative_Control                    => 51,
      Interpolation_Function                => 52,
      Transform_Feedback                    => 53,
      Geometry_Streams                      => 54,
      Storage_Image_Read_Without_Format     => 55,
      Storage_Image_Write_Without_Format    => 56);

   type Op is
     (Op_Nop,
      Op_Undef,
      Op_Source_Continued,
      Op_Source,
      Op_Source_Extension,
      Op_Name,
      Op_Member_Name,
      Op_String,
      Op_Line,
      Op_Extension,
      Op_Ext_Inst_Import,
      Op_Ext_Inst,
      Op_Memory_Model,
      Op_Entry_Point,
      Op_Execution_Mode,
      Op_Capability,
      Op_Type_Void,
      Op_Type_Bool,
      Op_Type_Int,
      Op_Type_Float,
      Op_Type_Vector,
      Op_Type_Matrix,
      Op_Type_Image,
      Op_Type_Sampler,
      Op_Type_Sampled_Image,
      Op_Type_Array,
      Op_Type_Runtime_Array,
      Op_Type_Struct,
      Op_Type_Opaque,
      Op_Type_Pointer,
      Op_Type_Function,
      Op_Type_Event,
      Op_Type_Device_Event,
      Op_Type_Reserve_Id,
      Op_Type_Queue,
      Op_Type_Pipe,
      Op_Type_Forward_Pointer,
      Op_Constant_True,
      Op_Constant_False,
      Op_Constant,
      Op_Constant_Composite,
      Op_Constant_Sampler,
      Op_Constant_Null,
      Op_Spec_Constant_True,
      Op_Spec_Constant_False,
      Op_Spec_Constant,
      Op_Spec_Constant_Composite,
      Op_Spec_Constant_Op,
      Op_Function,
      Op_Function_Parameter,
      Op_Function_End,
      Op_Function_Call,
      Op_Variable,
      Op_Image_Texel_Pointer,
      Op_Load,
      Op_Store,
      Op_Copy_Memory,
      Op_Copy_Memory_Sized,
      Op_Access_Chain,
      Op_In_Bounds_Access_Chain,
      Op_Ptr_Access_Chain,
      Op_Array_Length,
      Op_Generic_Ptr_Mem_Semantics,
      Op_In_Bounds_Ptr_Access_Chain,
      Op_Decorate,
      Op_Member_Decorate,
      Op_Decoration_Group,
      Op_Group_Decorate,
      Op_Group_Member_Decorate,
      Op_Vector_Extract_Dynamic,
      Op_Vector_Insert_Dynamic,
      Op_Vector_Shuffle,
      Op_Composite_Construct,
      Op_Composite_Extract,
      Op_Composite_Insert,
      Op_Copy_Object,
      Op_Transpose,
      Op_Sampled_Image,
      Op_Image_Sample_Implicit_LOD,
      Op_Image_Sample_Explicit_LOD,
      Op_Image_Sample_Dref_Implicit_LOD,
      Op_Image_Sample_Dref_Explicit_LOD,
      Op_Image_Sample_Proj_Implicit_LOD,
      Op_Image_Sample_Proj_Explicit_LOD,
      Op_Image_Sample_Proj_Dref_Implicit_LOD,
      Op_Image_Sample_Proj_Dref_Explicit_LOD,
      Op_Image_Fetch,
      Op_Image_Gather,
      Op_Image_Dref_Gather,
      Op_Image_Read,
      Op_Image_Write,
      Op_Image,
      Op_Image_Query_Format,
      Op_Image_Query_Order,
      Op_Image_Query_Size_LOD,
      Op_Image_Query_Size,
      Op_Image_Query_Lod,
      Op_Image_Query_Levels,
      Op_Image_Query_Samples,
      Op_Convert_F_To_U,
      Op_Convert_F_To_S,
      Op_Convert_S_To_F,
      Op_Convert_U_To_F,
      Op_U_Convert,
      Op_S_Convert,
      Op_F_Convert,
      Op_Quantize_To_F16,
      Op_Convert_Ptr_To_U,
      Op_Sat_Convert_S_To_U,
      Op_Sat_Convert_U_To_S,
      Op_Convert_U_To_Ptr,
      Op_Ptr_Cast_To_Generic,
      Op_Generic_Cast_To_Ptr,
      Op_Generic_Cast_To_Ptr_Explicit,
      Op_Bitcast,
      Op_S_Negate,
      Op_F_Negate,
      Op_I_Add,
      Op_F_Add,
      Op_I_Sub,
      Op_F_Sub,
      Op_I_Mul,
      Op_F_Mul,
      Op_U_Div,
      Op_S_Div,
      Op_F_Div,
      Op_U_Mod,
      Op_S_Rem,
      Op_S_Mod,
      Op_F_Rem,
      Op_F_Mod,
      Op_Vector_Times_Scalar,
      Op_Matrix_Times_Scalar,
      Op_Vector_Times_Matrix,
      Op_Matrix_Times_Vector,
      Op_Matrix_Times_Matrix,
      Op_Outer_Product,
      Op_Dot,
      Op_I_Add_Carry,
      Op_I_Sub_Borrow,
      Op_U_Mul_Extended,
      Op_S_Mul_Extended,
      Op_Any,
      Op_All,
      Op_Is_Nan,
      Op_Is_Inf,
      Op_Is_Finite,
      Op_Is_Normal,
      Op_Sign_Bit_Set,
      Op_Less_Or_Greater,
      Op_Ordered,
      Op_Unordered,
      Op_Logical_Equal,
      Op_Logical_Not_Equal,
      Op_Logical_Or,
      Op_Logical_And,
      Op_Logical_Not,
      Op_Select,
      Op_I_Equal,
      Op_I_Not_Equal,
      Op_U_Greater_Than,
      Op_S_Greater_Than,
      Op_U_Greater_Than_Equal,
      Op_S_Greater_Than_Equal,
      Op_U_Less_Than,
      Op_S_Less_Than,
      Op_U_Less_Than_Equal,
      Op_S_Less_Than_Equal,
      Op_F_Ord_Equal,
      Op_F_Unord_Equal,
      Op_F_Ord_Not_Equal,
      Op_F_Unord_Not_Equal,
      Op_F_Ord_Less_Than,
      Op_F_Unord_Less_Than,
      Op_F_Ord_Greater_Than,
      Op_F_Unord_Greater_Than,
      Op_F_Ord_Less_Than_Equal,
      Op_F_Unord_Less_Than_Equal,
      Op_F_Ord_Greater_Than_Equal,
      Op_F_Unord_Greater_Than_Equal,
      Op_Shift_Right_Logical,
      Op_Shift_Right_Arithmetic,
      Op_Shift_Left_Logical,
      Op_Bitwise_Or,
      Op_Bitwise_Xor,
      Op_Bitwise_And,
      Op_Not,
      Op_Bit_Field_Insert,
      Op_Bit_Field_S_Extract,
      Op_Bit_Field_U_Extract,
      Op_Bit_Reverse,
      Op_Bit_Count,
      Op_DPdx,
      Op_DPdy,
      Op_Fwidth,
      Op_DPdx_Fine,
      Op_DPdy_Fine,
      Op_Fwidth_Fine,
      Op_DPdx_Coarse,
      Op_DPdy_Coarse,
      Op_Fwidth_Coarse,
      Op_Emit_Vertex,
      Op_End_Primitive,
      Op_Emit_Stream_Vertex,
      Op_End_Stream_Primitive,
      Op_Control_Barrier,
      Op_Memory_Barrier,
      Op_Atomic_Load,
      Op_Atomic_Store,
      Op_Atomic_Exchange,
      Op_Atomic_Compare_Exchange,
      Op_Atomic_Compare_Exchange_Weak,
      Op_Atomic_I_Increment,
      Op_Atomic_I_Decrement,
      Op_Atomic_I_Add,
      Op_Atomic_I_Sub,
      Op_Atomic_S_Min,
      Op_Atomic_U_Min,
      Op_Atomic_S_Max,
      Op_Atomic_U_Max,
      Op_Atomic_And,
      Op_Atomic_Or,
      Op_Atomic_Xor,
      Op_Phi,
      Op_Loop_Merge,
      Op_Selection_Merge,
      Op_Label,
      Op_Branch,
      Op_Branch_Conditional,
      Op_Switch,
      Op_Kill,
      Op_Return,
      Op_Return_Value,
      Op_Unreachable,
      Op_Lifetime_Start,
      Op_Lifetime_Stop,
      Op_Group_Async_Copy,
      Op_Group_Wait_Events,
      Op_Group_All,
      Op_Group_Any,
      Op_Group_Broadcast,
      Op_Group_I_Add,
      Op_Group_F_Add,
      Op_Group_F_Min,
      Op_Group_U_Min,
      Op_Group_S_Min,
      Op_Group_F_Max,
      Op_Group_U_Max,
      Op_Group_S_Max,
      Op_Read_Pipe,
      Op_Write_Pipe,
      Op_Reserved_Read_Pipe,
      Op_Reserved_Write_Pipe,
      Op_Reserve_Read_Pipe_Packets,
      Op_Reserve_Write_Pipe_Packets,
      Op_Commit_Read_Pipe,
      Op_Commit_Write_Pipe,
      Op_Is_Valid_Reserve_Id,
      Op_Get_Num_Pipe_Packets,
      Op_Get_Max_Pipe_Packets,
      Op_Group_Reserve_Read_Pipe_Packets,
      Op_Group_Reserve_Write_Pipe_Packets,
      Op_Group_Commit_Read_Pipe,
      Op_Group_Commit_Write_Pipe,
      Op_Enqueue_Marker,
      Op_Enqueue_Kernel,
      Op_Get_Kernel_ND_Range_Sub_Group_Count,
      Op_Get_Kernel_ND_Range_Max_Sub_Group_Size,
      Op_Get_Kernel_Work_Group_Size,
      Op_Get_Kernel_Preferred_Work_Group_Size_Multiple,
      Op_Retain_Event,
      Op_Release_Event,
      Op_Create_User_Event,
      Op_Is_Valid_Event,
      Op_Set_User_Event_Status,
      Op_Capture_Event_Profiling_Info,
      Op_Get_Default_Queue,
      Op_Build_ND_Range,
      Op_Image_Sparse_Sample_Implicit_LOD,
      Op_Image_Sparse_Sample_Explicit_LOD,
      Op_Image_Sparse_Sample_Dref_Implicit_LOD,
      Op_Image_Sparse_Sample_Dref_Explicit_LOD,
      Op_Image_Sparse_Sample_Proj_Implicit_LOD,
      Op_Image_Sparse_Sample_Proj_Explicit_LOD,
      Op_Image_Sparse_Sample_Proj_Dref_Implicit_LOD,
      Op_Image_Sparse_Sample_Proj_Dref_Explicit_LOD,
      Op_Image_Sparse_Fetch,
      Op_Image_Sparse_Gather,
      Op_Image_Sparse_Dref_Gather,
      Op_Image_Sparse_Texels_Resident,
      Op_No_Line,
      Op_Atomic_Flag_Test_And_Set,
      Op_Atomic_Flag_Clear) with
     Convention => C;

   for Op use
     (Op_Nop                                           => 0,
      Op_Undef                                         => 1,
      Op_Source_Continued                              => 2,
      Op_Source                                        => 3,
      Op_Source_Extension                              => 4,
      Op_Name                                          => 5,
      Op_Member_Name                                   => 6,
      Op_String                                        => 7,
      Op_Line                                          => 8,
      Op_Extension                                     => 10,
      Op_Ext_Inst_Import                               => 11,
      Op_Ext_Inst                                      => 12,
      Op_Memory_Model                                  => 14,
      Op_Entry_Point                                   => 15,
      Op_Execution_Mode                                => 16,
      Op_Capability                                    => 17,
      Op_Type_Void                                     => 19,
      Op_Type_Bool                                     => 20,
      Op_Type_Int                                      => 21,
      Op_Type_Float                                    => 22,
      Op_Type_Vector                                   => 23,
      Op_Type_Matrix                                   => 24,
      Op_Type_Image                                    => 25,
      Op_Type_Sampler                                  => 26,
      Op_Type_Sampled_Image                            => 27,
      Op_Type_Array                                    => 28,
      Op_Type_Runtime_Array                            => 29,
      Op_Type_Struct                                   => 30,
      Op_Type_Opaque                                   => 31,
      Op_Type_Pointer                                  => 32,
      Op_Type_Function                                 => 33,
      Op_Type_Event                                    => 34,
      Op_Type_Device_Event                             => 35,
      Op_Type_Reserve_Id                               => 36,
      Op_Type_Queue                                    => 37,
      Op_Type_Pipe                                     => 38,
      Op_Type_Forward_Pointer                          => 39,
      Op_Constant_True                                 => 41,
      Op_Constant_False                                => 42,
      Op_Constant                                      => 43,
      Op_Constant_Composite                            => 44,
      Op_Constant_Sampler                              => 45,
      Op_Constant_Null                                 => 46,
      Op_Spec_Constant_True                            => 48,
      Op_Spec_Constant_False                           => 49,
      Op_Spec_Constant                                 => 50,
      Op_Spec_Constant_Composite                       => 51,
      Op_Spec_Constant_Op                              => 52,
      Op_Function                                      => 54,
      Op_Function_Parameter                            => 55,
      Op_Function_End                                  => 56,
      Op_Function_Call                                 => 57,
      Op_Variable                                      => 59,
      Op_Image_Texel_Pointer                           => 60,
      Op_Load                                          => 61,
      Op_Store                                         => 62,
      Op_Copy_Memory                                   => 63,
      Op_Copy_Memory_Sized                             => 64,
      Op_Access_Chain                                  => 65,
      Op_In_Bounds_Access_Chain                        => 66,
      Op_Ptr_Access_Chain                              => 67,
      Op_Array_Length                                  => 68,
      Op_Generic_Ptr_Mem_Semantics                     => 69,
      Op_In_Bounds_Ptr_Access_Chain                    => 70,
      Op_Decorate                                      => 71,
      Op_Member_Decorate                               => 72,
      Op_Decoration_Group                              => 73,
      Op_Group_Decorate                                => 74,
      Op_Group_Member_Decorate                         => 75,
      Op_Vector_Extract_Dynamic                        => 77,
      Op_Vector_Insert_Dynamic                         => 78,
      Op_Vector_Shuffle                                => 79,
      Op_Composite_Construct                           => 80,
      Op_Composite_Extract                             => 81,
      Op_Composite_Insert                              => 82,
      Op_Copy_Object                                   => 83,
      Op_Transpose                                     => 84,
      Op_Sampled_Image                                 => 86,
      Op_Image_Sample_Implicit_LOD                     => 87,
      Op_Image_Sample_Explicit_LOD                     => 88,
      Op_Image_Sample_Dref_Implicit_LOD                => 89,
      Op_Image_Sample_Dref_Explicit_LOD                => 90,
      Op_Image_Sample_Proj_Implicit_LOD                => 91,
      Op_Image_Sample_Proj_Explicit_LOD                => 92,
      Op_Image_Sample_Proj_Dref_Implicit_LOD           => 93,
      Op_Image_Sample_Proj_Dref_Explicit_LOD           => 94,
      Op_Image_Fetch                                   => 95,
      Op_Image_Gather                                  => 96,
      Op_Image_Dref_Gather                             => 97,
      Op_Image_Read                                    => 98,
      Op_Image_Write                                   => 99,
      Op_Image                                         => 100,
      Op_Image_Query_Format                            => 101,
      Op_Image_Query_Order                             => 102,
      Op_Image_Query_Size_LOD                          => 103,
      Op_Image_Query_Size                              => 104,
      Op_Image_Query_Lod                               => 105,
      Op_Image_Query_Levels                            => 106,
      Op_Image_Query_Samples                           => 107,
      Op_Convert_F_To_U                                => 109,
      Op_Convert_F_To_S                                => 110,
      Op_Convert_S_To_F                                => 111,
      Op_Convert_U_To_F                                => 112,
      Op_U_Convert                                     => 113,
      Op_S_Convert                                     => 114,
      Op_F_Convert                                     => 115,
      Op_Quantize_To_F16                               => 116,
      Op_Convert_Ptr_To_U                              => 117,
      Op_Sat_Convert_S_To_U                            => 118,
      Op_Sat_Convert_U_To_S                            => 119,
      Op_Convert_U_To_Ptr                              => 120,
      Op_Ptr_Cast_To_Generic                           => 121,
      Op_Generic_Cast_To_Ptr                           => 122,
      Op_Generic_Cast_To_Ptr_Explicit                  => 123,
      Op_Bitcast                                       => 124,
      Op_S_Negate                                      => 126,
      Op_F_Negate                                      => 127,
      Op_I_Add                                         => 128,
      Op_F_Add                                         => 129,
      Op_I_Sub                                         => 130,
      Op_F_Sub                                         => 131,
      Op_I_Mul                                         => 132,
      Op_F_Mul                                         => 133,
      Op_U_Div                                         => 134,
      Op_S_Div                                         => 135,
      Op_F_Div                                         => 136,
      Op_U_Mod                                         => 137,
      Op_S_Rem                                         => 138,
      Op_S_Mod                                         => 139,
      Op_F_Rem                                         => 140,
      Op_F_Mod                                         => 141,
      Op_Vector_Times_Scalar                           => 142,
      Op_Matrix_Times_Scalar                           => 143,
      Op_Vector_Times_Matrix                           => 144,
      Op_Matrix_Times_Vector                           => 145,
      Op_Matrix_Times_Matrix                           => 146,
      Op_Outer_Product                                 => 147,
      Op_Dot                                           => 148,
      Op_I_Add_Carry                                   => 149,
      Op_I_Sub_Borrow                                  => 150,
      Op_U_Mul_Extended                                => 151,
      Op_S_Mul_Extended                                => 152,
      Op_Any                                           => 154,
      Op_All                                           => 155,
      Op_Is_Nan                                        => 156,
      Op_Is_Inf                                        => 157,
      Op_Is_Finite                                     => 158,
      Op_Is_Normal                                     => 159,
      Op_Sign_Bit_Set                                  => 160,
      Op_Less_Or_Greater                               => 161,
      Op_Ordered                                       => 162,
      Op_Unordered                                     => 163,
      Op_Logical_Equal                                 => 164,
      Op_Logical_Not_Equal                             => 165,
      Op_Logical_Or                                    => 166,
      Op_Logical_And                                   => 167,
      Op_Logical_Not                                   => 168,
      Op_Select                                        => 169,
      Op_I_Equal                                       => 170,
      Op_I_Not_Equal                                   => 171,
      Op_U_Greater_Than                                => 172,
      Op_S_Greater_Than                                => 173,
      Op_U_Greater_Than_Equal                          => 174,
      Op_S_Greater_Than_Equal                          => 175,
      Op_U_Less_Than                                   => 176,
      Op_S_Less_Than                                   => 177,
      Op_U_Less_Than_Equal                             => 178,
      Op_S_Less_Than_Equal                             => 179,
      Op_F_Ord_Equal                                   => 180,
      Op_F_Unord_Equal                                 => 181,
      Op_F_Ord_Not_Equal                               => 182,
      Op_F_Unord_Not_Equal                             => 183,
      Op_F_Ord_Less_Than                               => 184,
      Op_F_Unord_Less_Than                             => 185,
      Op_F_Ord_Greater_Than                            => 186,
      Op_F_Unord_Greater_Than                          => 187,
      Op_F_Ord_Less_Than_Equal                         => 188,
      Op_F_Unord_Less_Than_Equal                       => 189,
      Op_F_Ord_Greater_Than_Equal                      => 190,
      Op_F_Unord_Greater_Than_Equal                    => 191,
      Op_Shift_Right_Logical                           => 194,
      Op_Shift_Right_Arithmetic                        => 195,
      Op_Shift_Left_Logical                            => 196,
      Op_Bitwise_Or                                    => 197,
      Op_Bitwise_Xor                                   => 198,
      Op_Bitwise_And                                   => 199,
      Op_Not                                           => 200,
      Op_Bit_Field_Insert                              => 201,
      Op_Bit_Field_S_Extract                           => 202,
      Op_Bit_Field_U_Extract                           => 203,
      Op_Bit_Reverse                                   => 204,
      Op_Bit_Count                                     => 205,
      Op_DPdx                                          => 207,
      Op_DPdy                                          => 208,
      Op_Fwidth                                        => 209,
      Op_DPdx_Fine                                     => 210,
      Op_DPdy_Fine                                     => 211,
      Op_Fwidth_Fine                                   => 212,
      Op_DPdx_Coarse                                   => 213,
      Op_DPdy_Coarse                                   => 214,
      Op_Fwidth_Coarse                                 => 215,
      Op_Emit_Vertex                                   => 218,
      Op_End_Primitive                                 => 219,
      Op_Emit_Stream_Vertex                            => 220,
      Op_End_Stream_Primitive                          => 221,
      Op_Control_Barrier                               => 224,
      Op_Memory_Barrier                                => 225,
      Op_Atomic_Load                                   => 227,
      Op_Atomic_Store                                  => 228,
      Op_Atomic_Exchange                               => 229,
      Op_Atomic_Compare_Exchange                       => 230,
      Op_Atomic_Compare_Exchange_Weak                  => 231,
      Op_Atomic_I_Increment                            => 232,
      Op_Atomic_I_Decrement                            => 233,
      Op_Atomic_I_Add                                  => 234,
      Op_Atomic_I_Sub                                  => 235,
      Op_Atomic_S_Min                                  => 236,
      Op_Atomic_U_Min                                  => 237,
      Op_Atomic_S_Max                                  => 238,
      Op_Atomic_U_Max                                  => 239,
      Op_Atomic_And                                    => 240,
      Op_Atomic_Or                                     => 241,
      Op_Atomic_Xor                                    => 242,
      Op_Phi                                           => 245,
      Op_Loop_Merge                                    => 246,
      Op_Selection_Merge                               => 247,
      Op_Label                                         => 248,
      Op_Branch                                        => 249,
      Op_Branch_Conditional                            => 250,
      Op_Switch                                        => 251,
      Op_Kill                                          => 252,
      Op_Return                                        => 253,
      Op_Return_Value                                  => 254,
      Op_Unreachable                                   => 255,
      Op_Lifetime_Start                                => 256,
      Op_Lifetime_Stop                                 => 257,
      Op_Group_Async_Copy                              => 259,
      Op_Group_Wait_Events                             => 260,
      Op_Group_All                                     => 261,
      Op_Group_Any                                     => 262,
      Op_Group_Broadcast                               => 263,
      Op_Group_I_Add                                   => 264,
      Op_Group_F_Add                                   => 265,
      Op_Group_F_Min                                   => 266,
      Op_Group_U_Min                                   => 267,
      Op_Group_S_Min                                   => 268,
      Op_Group_F_Max                                   => 269,
      Op_Group_U_Max                                   => 270,
      Op_Group_S_Max                                   => 271,
      Op_Read_Pipe                                     => 274,
      Op_Write_Pipe                                    => 275,
      Op_Reserved_Read_Pipe                            => 276,
      Op_Reserved_Write_Pipe                           => 277,
      Op_Reserve_Read_Pipe_Packets                     => 278,
      Op_Reserve_Write_Pipe_Packets                    => 279,
      Op_Commit_Read_Pipe                              => 280,
      Op_Commit_Write_Pipe                             => 281,
      Op_Is_Valid_Reserve_Id                           => 282,
      Op_Get_Num_Pipe_Packets                          => 283,
      Op_Get_Max_Pipe_Packets                          => 284,
      Op_Group_Reserve_Read_Pipe_Packets               => 285,
      Op_Group_Reserve_Write_Pipe_Packets              => 286,
      Op_Group_Commit_Read_Pipe                        => 287,
      Op_Group_Commit_Write_Pipe                       => 288,
      Op_Enqueue_Marker                                => 291,
      Op_Enqueue_Kernel                                => 292,
      Op_Get_Kernel_ND_Range_Sub_Group_Count           => 293,
      Op_Get_Kernel_ND_Range_Max_Sub_Group_Size        => 294,
      Op_Get_Kernel_Work_Group_Size                    => 295,
      Op_Get_Kernel_Preferred_Work_Group_Size_Multiple => 296,
      Op_Retain_Event                                  => 297,
      Op_Release_Event                                 => 298,
      Op_Create_User_Event                             => 299,
      Op_Is_Valid_Event                                => 300,
      Op_Set_User_Event_Status                         => 301,
      Op_Capture_Event_Profiling_Info                  => 302,
      Op_Get_Default_Queue                             => 303,
      Op_Build_ND_Range                                => 304,
      Op_Image_Sparse_Sample_Implicit_LOD              => 305,
      Op_Image_Sparse_Sample_Explicit_LOD              => 306,
      Op_Image_Sparse_Sample_Dref_Implicit_LOD         => 307,
      Op_Image_Sparse_Sample_Dref_Explicit_LOD         => 308,
      Op_Image_Sparse_Sample_Proj_Implicit_LOD         => 309,
      Op_Image_Sparse_Sample_Proj_Explicit_LOD         => 310,
      Op_Image_Sparse_Sample_Proj_Dref_Implicit_LOD    => 311,
      Op_Image_Sparse_Sample_Proj_Dref_Explicit_LOD    => 312,
      Op_Image_Sparse_Fetch                            => 313,
      Op_Image_Sparse_Gather                           => 314,
      Op_Image_Sparse_Dref_Gather                      => 315,
      Op_Image_Sparse_Texels_Resident                  => 316,
      Op_No_Line                                       => 317,
      Op_Atomic_Flag_Test_And_Set                      => 318,
      Op_Atomic_Flag_Clear                             => 319);
end SPIRV;
